{% set name = "colcon-defaults" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 0d30bf3a8d0e57be8ad0149363c5635b20d0ec0d83965b3679056fb376eadf82

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - colcon-core >=0.2.0
    - PyYAML

test:
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    An extension for colcon-core to provide custom default
    values for the command line arguments from a configuration file.

extra:
  recipe-maintainers:
    - j-rivero
    - seanyen
    - wolfv
